[bot]
token = "TOKEN"
owners = [ "000000000000000000" ]


[auth]
# 認証の結果を通知するチャンネルID
log_channel_id = "000000000000000000"
# 認証後に付与するロールID
role_id = "000000000000000000"
# マッチしたら認証成功とする文字列
trigger = "おのれGreg"
# モーダルのデフォルト値にランダムに選択させるダミーのキーワード群
dummy_keywords = [ "ダミー", "dummy" ]


[auto_kick]
# 参加してからキックされるまでの猶予時間 (例: "12h" なら12時間) (1時間に一度チェックされる)
grace_period = "12h"
# キックされた際にDMへ送信するメッセージ
kick_message = """てすとサーバー にて合言葉の入力が確認できなかったため、自動的にキックされました。
再度参加する場合は、以下のリンクから再度参加してください。
https://example.com/
"""


[message_logging]
# メッセージの削除・編集のログを残すチャンネルID
channel_id = "000000000000000000"


[message_cache]
# 過去メッセージのキャッシュを無効化するかどうか
disabled = false
# 過去メッセージのキャッシュ取らないチャンネルIDのリスト、親チャンネルを指定すると子のチャンネルも対象 (孫は対象外)
ignore_channel_ids = [ "000000000000000000" ]


[thread_channel_startup]
# 初期メッセージを投稿するスレッドチャンネルのID
channel_id = "000000000000000000"
# 初期メッセージの内容
startup_message = """スレッドの始まりだぁ！
まずはこのテンプレートを読んでね！"""


[thread_auto_invite]
# 実際に呼び出されるロールのID
role_ids = [ "000000000000000000", "000000000000000000" ]


[forum_cache]
# キャッシュ対象のフォーラムチャンネルID
channels = [ {channel_id = "000000000000000000", limit = 100} ]


[question]
# 質問の投稿先フォーラムのID
forum_id = "000000000000000000"
# 解決済みのタグID
solved_tag = "000000000000000000"


[DB]
# DBの接続文字列
connection = "postgresql://user:password@localhost:5432/mydb"
# スキーマ
schema = "bot"